# Generated by Django 6.0.3 on 2026-03-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_delivered_message_is_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
